### ISSUE TITLE
Support Tailwind CSS v4

### ISSUE THREAD

**Issue by RihanArfan** [nuxt/fonts#132]
Tailwind v4 moves configuration into CSS instead of `tailwind.config.js`. https://tailwindcss.com/blog/tailwindcss-v4-alpha

For example in v4 to specify a custom font, you'd just do this and then you can use `.font-display` within your HTML. (example from their blog post)
```css
/* main.css */
@import "tailwindcss";

@theme {
  --font-family-display: "Satoshi", "sans-serif";
}
```
### Workaround

Currently the workaround to use Tailwind CSS v4 with Nuxt Fonts is simply to specify using `font-family` in the CSS so it's loaded in.
```css
@import "tailwindcss";

@theme {
  --font-family-marker: "Permanent Marker", cursive;
}

.nuxt-fonts-permanent-marker {
  font-family: "Permanent Marker", cursive;
}
```
