### ISSUE TITLE
adobe fonts with differing name information not loading

### ISSUE THREAD

**Issue by ThunderDino1** [nuxt/fonts#340]
I'm currently trying to add the adobe font "Elena" to my project, without success. 
My searched led me to [#187](https://github.com/nuxt/fonts/issues/187) and it's fix [#192](https://github.com/nuxt/fonts/pull/192) but to no avail.

would kindly appreciate your help :)

my nuxt.config.ts fonts //config:

```js
fonts: {
        defaults: {
            weights: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
            styles: ['normal', 'italic'],
        },
        adobe: {
            id: ['xxxxxx'],
        },
        fonts: {
            experimental: {
                processCSSVariables: true, // <-- tested if that made a difference
            },
        },
        families: [
            {
                name: 'Industry',
                provider: 'adobe',
                fallbacks: ['Oswald', 'Arial', 'Helvetica', 'sans-serif'],
            },
            {
                name: 'Elena Web Basic', <--- tested "Elena", "Elena Basic", "Elena-Web-Basic"
                provider: 'adobe',
                fallbacks: ['Georgia', 'Times New Roman', 'serif'],
            },
            {
                name: 'Oswald',
                provider: 'google',
                fallbacks: ['Roboto Sans', 'Arial', 'Helvetica', 'sans-serif'],
            },
        ],
    },
```

```js
Tailwind Config:

`extend: {
            fontFamily: {
                display: ['Industry', 'Oswald', 'Arial', 'Helvetica', 'sans-serif'],
                serif: ['"Elena Web Basic"', 'Georgia', 'Times New Roman', 'serif'], //<-- also tried "Elena", "Elena Basic", "Elena-Web-Basic"
            },`
```

the typekit css:

```css
@import url("https://p.typekit.net/p.css?s=1&k=dou8fmt&ht=tk&f=25310.25314.14437.14439&a=8358342&app=typekit&e=css");

@font-face {
font-family:"industry";
src:url("https://use.typekit.net/af/99114e/000000000000000077519a43/30/l?primer=7cdcb44be4a7db8877ffa5c0007b8dd865b3bbc383831fe2ea177f62257a9191&fvd=n7&v=3") format("woff2"),url("https://use.typekit.net/af/99114e/000000000000000077519a43/30/d?primer=7cdcb44be4a7db8877ffa5c0007b8dd865b3bbc383831fe2ea177f62257a9191&fvd=n7&v=3") format("woff"),url("https://use.typekit.net/af/99114e/000000000000000077519a43/30/a?primer=7cdcb44be4a7db8877ffa5c0007b8dd865b3bbc383831fe2ea177f62257a9191&fvd=n7&v=3") format("opentype");
font-display:auto;font-style:normal;font-weight:700;font-stretch:normal;
}

@font-face {
font-family:"industry";
src:url("https://use.typekit.net/af/e15078/000000000000000077519a3f/30/l?primer=7cdcb44be4a7db8877ffa5c0007b8dd865b3bbc383831fe2ea177f62257a9191&fvd=n6&v=3") format("woff2"),url("https://use.typekit.net/af/e15078/000000000000000077519a3f/30/d?primer=7cdcb44be4a7db8877ffa5c0007b8dd865b3bbc383831fe2ea177f62257a9191&fvd=n6&v=3") format("woff"),url("https://use.typekit.net/af/e15078/000000000000000077519a3f/30/a?primer=7cdcb44be4a7db8877ffa5c0007b8dd865b3bbc383831fe2ea177f62257a9191&fvd=n6&v=3") format("opentype");
font-display:auto;font-style:normal;font-weight:600;font-stretch:normal;
}

@font-face {
font-family:"elena-web-basic";
src:url("https://use.typekit.net/af/5d3cbc/00000000000000007735daea/30/l?primer=7cdcb44be4a7db8877ffa5c0007b8dd865b3bbc383831fe2ea177f62257a9191&fvd=n7&v=3") format("woff2"),url("https://use.typekit.net/af/5d3cbc/00000000000000007735daea/30/d?primer=7cdcb44be4a7db8877ffa5c0007b8dd865b3bbc383831fe2ea177f62257a9191&fvd=n7&v=3") format("woff"),url("https://use.typekit.net/af/5d3cbc/00000000000000007735daea/30/a?primer=7cdcb44be4a7db8877ffa5c0007b8dd865b3bbc383831fe2ea177f62257a9191&fvd=n7&v=3") format("opentype");
font-display:auto;font-style:normal;font-weight:700;font-stretch:normal;
}

@font-face {
font-family:"elena-web-basic";
src:url("https://use.typekit.net/af/d89e6b/00000000000000007735daec/30/l?primer=7cdcb44be4a7db8877ffa5c0007b8dd865b3bbc383831fe2ea177f62257a9191&fvd=n4&v=3") format("woff2"),url("https://use.typekit.net/af/d89e6b/00000000000000007735daec/30/d?primer=7cdcb44be4a7db8877ffa5c0007b8dd865b3bbc383831fe2ea177f62257a9191&fvd=n4&v=3") format("woff"),url("https://use.typekit.net/af/d89e6b/00000000000000007735daec/30/a?primer=7cdcb44be4a7db8877ffa5c0007b8dd865b3bbc383831fe2ea177f62257a9191&fvd=n4&v=3") format("opentype");
font-display:auto;font-style:normal;font-weight:400;font-stretch:normal;
}

.tk-industry { font-family: "industry",sans-serif; }
.tk-elena-web-basic { font-family: "elena-web-basic",serif; }`

```
