### ISSUE TITLE
Does not respect app.baseURL in inline font-face rules in production

### ISSUE THREAD

**Issue by Luca-Sett** [nuxt/fonts#341]
Setting `baseURL: "/base-url/"` does not seem to work in production (works as expected in development).

### Development
```css
@font-face {
  ...
  src: local("Playfair Display Variable"), url("/base-url/_fonts/nuFiD-vYSZviVYUb_rj3ij__anPXDTjYgEM86xRbPQ-OBdH44Wijn.woff2") format(woff2);
  ...
}
```

![Image](https://github.com/user-attachments/assets/81a208c9-5307-4214-ae05-49ee79d2048a)

### Production
```css
@font-face {
  ...
  src: local("Playfair Display Variable"), url(/_fonts/nuFiD-vYSZviVYUb_rj3ij__anPXDTjYgEM86xRbPQ-OBdH44Wijn.woff2) format(woff2);
  ...
}
```

![Image](https://github.com/user-attachments/assets/0cd7107c-a121-46b0-b8c3-58358a831137)

### Minimal reproduction
Repo: https://github.com/Luca-Sett/font-test
Live URL: https://font-test-beta.vercel.app/base-url/
