### ISSUE TITLE
How to change default font?

### ISSUE THREAD

**Issue by JenuelDev** [nuxt/fonts#478]
I like to change the default font. So that I dont have to set it in every page or layout. How do I do that?

**Comment by danielroe** [comment]
```css
// app.vue
:root {
  font-family: Poppins, sans-serif;
}
```

**Comment by JenuelDev** [comment]
I also discovered, that I can use it in my css file inside my `assets/style/main.scss`.
```scss
html {
    font-family: Poppins, sans-serif;
}
```
