### ISSUE TITLE
refused to apply style

### ISSUE THREAD

**Issue by moshetanzer** [nuxt/fonts#629]
Hey Daniel,

hope you keeping well

not sure exaclty when this started but in last version or two - and fonts do not display. Am using latest version of Nuxt fonts. 

````
Refused to apply style from 'http://localhost:3000/_nuxt/virtual:nuxt:C%3A%2FUsers%2Fskals%2FDesktop%2Fnuxt%2F.nuxt%2Fnuxt-fonts-global.css' because its MIME type ('application/json') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
````

any hints?

**Comment by thiagonunesbatista** [comment]
The same problem happens here.

version: `  "@nuxt/fonts": "^0.11.4"`

 I have a global CSS file to Tailwind, I thought It was the problem, but It wasn't the problem:

```css
@tailwind base;
@tailwind components;
@tailwind utilities;

* {
  font-family: "Poppins", sans-serif;
}
```
