### ISSUE TITLE
Local fonts with TailwindCSS v4 not loaded if using @theme inline

### ISSUE THREAD

**Issue by hendrasan** [nuxt/fonts#638]
Not sure if this is a bug or just me, but I found that when I used local fonts (put inside /public/fonts directory), and have this in my main.css

```
@theme inline {
  --font-sans: "Roboto", sans-serif;
}
```

It's not loaded. But if I do this:

```
@theme {
  --font-sans: "Roboto", sans-serif;
}
```

It works.

**Comment by thiagonunesbatista** [comment]
I have a similar problem, I wrote more details on the comment on other issue: https://github.com/nuxt/fonts/issues/706#issuecomment-3430160586

**Comment by rozsazoltan** [comment]
With `@theme inline`, the compiled CSS that Nuxt Fonts uses is different. In this case, the value `"Roboto", sans-serif` is actually written in place of `--default-font-family`. Nuxt Fonts rightfully doesn't pick this up, although this is closely related to this discovery:
* [Nuxt Fonts does not generate the correct @font-face when the font is set as the default font in TailwindCSS v4](https://stackoverflow.com/q/79878969/15167500)

**Input**
```css
@theme inline {
  --font-sans: "Roboto", sans-serif;
}
```

**Generated CSS** (Nuxt Fonts works based on this)
```css
@layer theme {
  :root, :host {
    --default-font-family: "Roboto", sans-serif; /* does not trigger a download */
  }
}
@layer base {
  :root, :host {
    /* although it would trigger the download, the name of the font to be downloaded isn't clear from this, and can't be inferred either, since it's not expected that --default-font-family exists */
    font-family: var(--default-font-family, ui-sans-serif, system-ui, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji');
  }
}
```

However, if you've used the `font-sans` class at least once in your code, the .font-sans utility is also generated, where the value is passed directly to the font-family property, which Nuxt Fonts detects. In this case, it already works:

**Input**
```html
<div class="font-sans">...</div>
```
```css
@theme inline {
  --font-sans: "Roboto", sans-serif;
}
```

**Generated CSS** (Nuxt Fonts works based on this)
```css
@layer theme {
  :root, :host {
    --default-font-family: "Roboto", sans-serif; /* does not trigger a download */
  }
}
@layer utilities {
  .font-sans {
    font-family: "Roboto", sans-serif; /* triggers a download */
  }
}
@layer base {
  :root, :host {
    /* although it would trigger the download, the name of the font to be downloaded isn't clear from this, and can't be inferred either, since it's not expected that --default-font-family exists */
    font-family: var(--default-font-family, ui-sans-serif, system-ui, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji');
  }
}
```

With `@theme` instead of `@theme inline`, the `--font-sans` variable is always included in the source code (since it's inherited by `--default-font-family` by default, so `--font-sans` ends up in the generated CSS for this reason). I'm not a Nuxt Fonts expert, but what I realized is that Nuxt Fonts collects font names that are either assigned directly to the `font-family` property or declared in `--font-*` variables, which is why this discovery works in this case.

**Input**
```css
@theme {
  --font-sans: "Roboto", sans-serif;
}
```

**Generated CSS** (Nuxt Fonts works based on this)
```css
@layer theme {
  :root, :host {
    --font-sans: "Roboto", sans-serif; /* triggers a download */
    --default-font-family: var(--font-sans); /* does not trigger a download */
  }
}
@layer base {
  :root, :host {
    /* although it would trigger the download, the name of the font to be downloaded isn't clear from this, and can't be inferred either, since it's not expected that --default-font-family exists */
    font-family: var(--default-font-family, ui-sans-serif, system-ui, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji');
  }
}
```

Note: If you change `--default-font-family`, `--font-sans` won't be automatically included in the generated CSS until you either make it static or use it at least once.

In the mentioned [SO post](https://stackoverflow.com/q/79878969/15167500) (although the answer is primarily built around `--default-font-family`, I think it's still useful), I outline several ways to ensure that Nuxt Fonts detects your font family, but one thing is certain: the behavior described in the issue is consistent with the generated CSS. I wouldn't call it a bug, just a situation that isn't immediately obvious. Perhaps clearer documentation is needed.

I think in TailwindCSS v4 it would make sense to analyze the value of a variable named `--default-font-family` alongside the `--font-*` variables. This would avoid the error mentioned in the issue. I believe this is an edge case that would be good to handle without `preserveCSSVariable`. And yes, with `preserveCSSVariable` all CSS variables are already checked, so the error mentioned in the issue doesn't occur - but I think that's too much overhead just to detect a single variable.
